#version 430 core

layout(local_size_x=512, local_size_y=1, local_size_z=1) in;

layout(std430, binding=1) buffer Positions { vec4 positions[]; };
layout(std430, binding=2) buffer PredictedPositions { vec4 predictedPositions[]; };
layout(std430, binding=3) buffer Velocities { vec4 velocities[]; };
layout(std430, binding = 8) buffer SimulationParameters {
    float dt;
    float gravityAcceleration;
    float mass;
    float collisionDamping;
    float smoothingRadius;
    float targetDensity;
    float pressureMultiplier;
    float viscosityStrength;
    float nearDensityMultiplier;
    
    uint isInteracting;
    uint isPaused;
    float inputPositionX;
    float inputPositionY;
    float inputPositionZ;
    float interactionRadius;
    float interactionStrength;
    float jitter;

    uint particleCount;
    uint hashSize;
    float spacing;
    float particleRadius;
    float scaleX;
	float scaleY;
	float scaleZ;

	float boundaryCenterX;
	float boundaryCenterY;
	float boundaryCenterZ;
	float padding0; 

	float boundaryHalfX;
	float boundaryHalfY;
	float boundaryHalfZ;
	float padding1;
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= particleCount) return;

    velocities[i] += vec4(0.0, -gravityAcceleration * dt, 0.0, 0.0);
    predictedPositions[i] = positions[i] + velocities[i] * dt;
}
