#version 430 core

struct ParticleValues {
	float mass;
	float density;
	float nearDensity;
	float particleRadius;
	uint mergeFlag;
	uint tag; // 0 = KEEP, 1 = SPLIT, 2 = MERGE
	uint cooldown;
   
	float padding;
};

struct SimulationParameters {
	float dt;
	float gravityAcceleration;
	float mass;
	float collisionDamping;
	float smoothingRadius;
	float targetDensity;
	float pressureMultiplier;
	float viscosityStrength;
	float nearDensityMultiplier;
	uint isInteracting;
	uint isPaused;
	float inputPositionX;
	float inputPositionY;
	float inputPositionZ;
	float interactionRadius;
	float interactionStrength;

	float high_density_factor;
	float low_density_factor;
	float max_mass_factor;
	float min_mass_factor;

	uint cooldown_frames;

	uint initialParticleCount;       // constant
	uint currentParticleCount;	     // dynamic, can change due to merge/split
	uint maxParticleCount;           // constant
	uint lookupCapacity;             // constant, always a power of two >= maxParticleCount
	uint paddedCurrentParticleCount; // dynamic, always a power of two >= currentParticleCount
	uint hashSize;					 // constant
	uint mergeSplitCoefficient;		 // constant, coefficient for max/min particle count
	float spacing;
	float particleRadius;
	float boundaryX;
	float boundaryY;
	float boundaryZ;

	float padding1;
	float padding2;
	float padding3;
};

layout(local_size_x = 256) in;

layout(std430, binding = 1) buffer ValueData { ParticleValues valData[]; };
layout(std430, binding = 6) buffer SimParamsBuffer { SimulationParameters sim; };

void main() {
    uint i = gl_GlobalInvocationID.x;
    if (i >= sim.currentParticleCount) return;

	// If cooling down, tick down and force KEEP this frame.
    if (valData[i].cooldown > 0u) {
        valData[i].cooldown -= 1u;
        valData[i].tag = 0u;          // KEEP while cooling
        return;
    }

    float rho  = valData[i].density;
    float mass = valData[i].mass;

    float upper = sim.high_density_factor * sim.targetDensity;
    float lower = sim.low_density_factor  * sim.targetDensity;
    float minMass = sim.min_mass_factor * sim.mass;
    float maxMass = sim.max_mass_factor * sim.mass;

    // Too sparse -> split
    if (rho < lower && mass > minMass) {
        valData[i].tag = 1;
    }
    // Too dense -> merge
    else if (rho > upper && mass < maxMass) {
        valData[i].tag = 2;
    }
    // Just right -> keep
    else {
        valData[i].tag = 0;
    }
}